name: RegressÃ£o de Testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testes-e2e:
    runs-on: ubuntu-latest
    name: ExecuÃ§Ã£o de testes E2E

    steps:
      - run: echo "ğŸ‰ O job foi acionado automaticamente por um evento ${{ github.event_name }}."
      - run: echo "ğŸ§ Este job agora estÃ¡ sendo executado em um servidor ${{ runner.os }} hospedado pelo GitHub!"
      - run: echo "ğŸ” O nome de sua branch Ã© ${{ github.ref }} e seu repositÃ³rio Ã© ${{ github.repository }}."
      
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ O repositÃ³rio ${{ github.repository }} repositÃ³rio foi clonado para o executor (runner)."
      - run: echo "ğŸ–¥ï¸ O workflow agora estÃ¡ pronto para testar seu cÃ³digo no executor (runner)."

      - name: Instalar dependÃªncias
        run: npm install

      - name: Executar testes Cypress
        run: npx cypress run --spec "cypress/e2e/automationExercice/Regression_Excecice.feature"
      
        
